### ISSUE TITLE
What happened to the Blockchain ID wiki??

### ISSUE THREAD

**Issue by taoeffect** [blockstack-packages/blockchain-id-deprecated#3]
Dammit. You folks keep moving things and breaking links!

This used to exist: https://github.com/blockstack/blockstack/wiki/Blockchain-ID

And this is not the first time this has happened.

It's _extremely_ frustrating updating all the broken links, and it means that people get lost trying to find critically important information such as the Blockchain ID specification.

Can we please stop moving things around?

**Comment by shea256** [comment]
Ah, sorry! The entire wiki for Blockchain ID is now here:

https://github.com/blockstack/blockchain-id/wiki

**Comment by taoeffect** [comment]
Just re-created that page and placed that new link there. Thanks!
